create table `subscriptions` (
  `id` int not null auto_increment primary key,
  `user_id` varchar(36) not null,
  `provider` enum('stripe', 'paypal', 'mercadopago') not null,
  `provider_subscription_id` varchar(255) not null,
  `provider_customer_id` varchar(255) not null,
  `plan_id` varchar(50) not null,
  `status` enum('active', 'canceled', 'past_due', 'trialing', 'incomplete', 'incomplete_expired', 'unpaid', 'paused') not null,
  `current_period_start` timestamp not null,
  `current_period_end` timestamp not null,
  `provider_payment_method_id` varchar(255),
  `metadata` json,
  `canceled_at` timestamp null,
  `created_at` timestamp default current_timestamp,
  `updated_at` timestamp default current_timestamp on update current_timestamp,
  foreign key (`user_id`) references `user`(`id`) on delete cascade,
  unique key `subscriptions_provider_subscription_id_unique` (`provider`, `provider_subscription_id`),
  index `subscriptions_user_id_idx` (`user_id`),
  index `subscriptions_provider_customer_id_idx` (`provider`, `provider_customer_id`),
  index `subscriptions_status_idx` (`status`)
);
